const n=(name,fallback)=>process.env[name]==null||process.env[name]===''?fallback:Number(process.env[name]);
const b=(name,fallback)=>process.env[name]==null||process.env[name]===''?fallback:['1','true','yes','on'].includes(String(process.env[name]).toLowerCase());
const s=(name,fallback='')=>process.env[name]??fallback;
const csv=(name,fallback='')=>String(s(name,fallback)).split(',').map(x=>x.trim()).filter(Boolean);
export const SOL_MINT='So11111111111111111111111111111111111111112';
export const config={
  tradingMode:s('TRADING_MODE','paper').toLowerCase(), liveAck:s('LIVE_TRADING_ACK',''),
  bankroll:n('PAPER_BANKROLL_USD',11), maxDailyLoss:n('MAX_DAILY_LOSS_USD',3), minScore:n('MIN_SCORE',85), pollSeconds:n('POLL_SECONDS',30),
  livePositionUsd:n('LIVE_POSITION_USD',5), approvedEntryUsd:n('APPROVED_ENTRY_USD',5), minTradeUsd:n('MIN_TRADE_USD',n('EXECUTION_MIN_USD',5)), minSolReserve:n('MIN_SOL_RESERVE',0.003),
  microCapEntryEnabled:b('MICRO_CAP_ENTRY_ENABLED',true),microCapEntryUsd:n('MICRO_CAP_ENTRY_USD',5),microCapMinScore:n('MICRO_CAP_MIN_SCORE',72),microCapMinEarlyMarketScore:n('MICRO_CAP_MIN_EARLY_MARKET_SCORE',30),microCapMaxAgeMinutes:n('MICRO_CAP_MAX_AGE_MINUTES',15),microCapMinMarketCap:n('MICRO_CAP_MIN_MARKET_CAP_USD',3000),microCapMaxMarketCap:n('MICRO_CAP_MAX_MARKET_CAP_USD',20000),
  positionSizingMode:(()=>{const m=s('POSITION_SIZING_MODE','dynamic').toLowerCase();return m==='fixed'?'dynamic':m})(), targetPositionPct:n('TARGET_POSITION_PCT',3), maxPositionUsd:n('MAX_POSITION_USD',100), maxPositionToLiquidityPct:n('MAX_POSITION_TO_LIQUIDITY_PCT',0.5),
  dynamicMinPositionPct:n('DYNAMIC_MIN_POSITION_PCT',5), dynamicMaxPositionPct:n('DYNAMIC_MAX_POSITION_PCT',30), dynamicMaxPositionUsd:n('DYNAMIC_MAX_POSITION_USD',0), maxActivePositions:n('MAX_ACTIVE_POSITIONS',3), maxTotalExposurePct:n('MAX_TOTAL_EXPOSURE_PCT',60),
  hardStopPct:n('HARD_STOP_PCT',35), legacyStopLossPct:n('STOP_LOSS_PCT',35),
  profitTiers:[
    {gain:n('TP1_GAIN_PCT',10),sell:n('TP1_SELL_PCT',15)},
    {gain:n('TP2_GAIN_PCT',20),sell:n('TP2_SELL_PCT',20)},
    {gain:n('TP3_GAIN_PCT',35),sell:n('TP3_SELL_PCT',20)},
    {gain:n('TP4_GAIN_PCT',60),sell:n('TP4_SELL_PCT',20)}
  ], microProfitTiers:[
    {gain:n('MICRO_TP1_GAIN_PCT',10),sell:n('MICRO_TP1_SELL_PCT',20)},
    {gain:n('MICRO_TP2_GAIN_PCT',20),sell:n('MICRO_TP2_SELL_PCT',25)},
    {gain:n('MICRO_TP3_GAIN_PCT',35),sell:n('MICRO_TP3_SELL_PCT',25)},
    {gain:n('MICRO_TP4_GAIN_PCT',60),sell:n('MICRO_TP4_SELL_PCT',20)}
  ], moonBagPct:n('MOON_BAG_PCT',25),microMoonBagPct:n('MICRO_MOON_BAG_PCT',10), maxExitChunkUsd:n('MAX_EXIT_CHUNK_USD',100),
  positionRiskRecheckSeconds:n('POSITION_RISK_RECHECK_SECONDS',120),liquidityRecheckSeconds:n('LIQUIDITY_RECHECK_SECONDS',30),
  liquidityWarningDropPct:n('LIQUIDITY_WARNING_DROP_PCT',50),liquidityDangerDropPct:n('LIQUIDITY_DANGER_DROP_PCT',70),liquidityCriticalDropPct:n('LIQUIDITY_CRITICAL_DROP_PCT',85),liquidityConfirmationsRequired:n('LIQUIDITY_CONFIRMATIONS_REQUIRED',3),liquidityCriticalConfirmationsRequired:n('LIQUIDITY_CRITICAL_CONFIRMATIONS_REQUIRED',2),liquidityMinExitEfficiencyPct:n('LIQUIDITY_MIN_EXIT_EFFICIENCY_PCT',75),liquidityCriticalExitEfficiencyPct:n('LIQUIDITY_CRITICAL_EXIT_EFFICIENCY_PCT',60),liquidityConfirmPriceDropPct:n('LIQUIDITY_CONFIRM_PRICE_DROP_PCT',-15),liquidityMinBuySellRatio:n('LIQUIDITY_MIN_BUY_SELL_RATIO',0.6),
  maxTokenAgeMinutes:n('MAX_TOKEN_AGE_MINUTES',1440), minLiquidity:n('MIN_LIQUIDITY_USD',3000), min5mVolume:n('MIN_5M_VOLUME_USD',500), minMarketCap:n('MIN_MARKET_CAP_USD',3000), maxMarketCap:n('MAX_MARKET_CAP_USD',100000000),
  earlyMaxAgeMinutes:n('EARLY_MAX_AGE_MINUTES',30), earlyMaxMarketCap:n('EARLY_MAX_MARKET_CAP_USD',150000), momentumMinMarketCap:n('MOMENTUM_MIN_MARKET_CAP_USD',50000),
  earlyRunnerProfileMaxAgeMinutes:n('EARLY_RUNNER_PROFILE_MAX_AGE_MINUTES',15),earlyVolumeTopUsd:n('EARLY_VOLUME_TOP_USD',2500),earlyVolumeHighUsd:n('EARLY_VOLUME_HIGH_USD',1000),earlyVolumeMidUsd:n('EARLY_VOLUME_MID_USD',500),earlyVolumeLowUsd:n('EARLY_VOLUME_LOW_USD',200),earlyVolumeAccelStrong:n('EARLY_VOLUME_ACCEL_STRONG',2.5),earlyVolumeAccelMin:n('EARLY_VOLUME_ACCEL_MIN',1.5),earlyBuySellStrong:n('EARLY_BUY_SELL_STRONG',1.5),earlyBuySellMin:n('EARLY_BUY_SELL_MIN',1.2),earlyParticipationMinTrades:n('EARLY_PARTICIPATION_MIN_TRADES',12),earlyAvgTradeStrongUsd:n('EARLY_AVG_TRADE_STRONG_USD',40),earlyAvgTradeMinUsd:n('EARLY_AVG_TRADE_MIN_USD',15),earlyLiquidityGrowthStrongPct:n('EARLY_LIQUIDITY_GROWTH_STRONG_PCT',10),earlyLiquidityGrowthMinPct:n('EARLY_LIQUIDITY_GROWTH_MIN_PCT',3),earlyVolLiqStrong:n('EARLY_VOL_LIQ_STRONG',0.20),earlyVolLiqMin:n('EARLY_VOL_LIQ_MIN',0.08),
  heliusApiKey:s('HELIUS_API_KEY'), jupiterApiKey:s('JUPITER_API_KEY'), bs58PrivateKey:s('BS58_PRIVATE_KEY'), expectedWalletAddress:s('EXPECTED_WALLET_ADDRESS'), runOnce:process.env.RUN_ONCE==='1', dataDir:s('DATA_DIR','.'),port:n('PORT',3000),
  xPostingEnabled:b('X_POSTING_ENABLED',false),xApiKey:s('X_API_KEY'),xApiSecret:s('X_API_SECRET'),xAccessToken:s('X_ACCESS_TOKEN'),xAccessTokenSecret:s('X_ACCESS_TOKEN_SECRET'),xDailyReportHourUtc:n('X_DAILY_REPORT_HOUR_UTC',23),xIdlePostingEnabled:b('X_IDLE_POSTING_ENABLED',true),xIdlePostHours:n('X_IDLE_POST_HOURS',2),
  crossPlatformEnabled:b('CROSS_PLATFORM_RUNNER_ENABLED',true),crossPlatformBonusMax:n('CROSS_PLATFORM_BONUS_MAX',8),runnerFeedPollSeconds:n('RUNNER_FEED_POLL_SECONDS',60),runnerFeedMaxAddresses:n('RUNNER_FEED_MAX_ADDRESSES',120),runnerFeedEarlyReserve:n('RUNNER_FEED_EARLY_RESERVE',40),runnerFeedTrendReserve:n('RUNNER_FEED_TREND_RESERVE',50),
  discoveryMaxAddresses:n('DISCOVERY_MAX_ADDRESSES',150),discoveryBatchSize:n('DISCOVERY_BATCH_SIZE',30),discoveryEarlyReserve:n('DISCOVERY_EARLY_RESERVE',50),discoveryTrendReserve:n('DISCOVERY_TREND_RESERVE',45),discoveryRunnerReserve:n('DISCOVERY_RUNNER_RESERVE',35),
  runnerRadarEnabled:b('RUNNER_RADAR_ENABLED',true),runnerRadarMinLiquidity:n('RUNNER_RADAR_MIN_LIQUIDITY_USD',5000),runnerRadarMinMarketCap:n('RUNNER_RADAR_MIN_MARKET_CAP_USD',10000),runnerRadarMaxMarketCap:n('RUNNER_RADAR_MAX_MARKET_CAP_USD',25000000),runnerRadarMin5mVolume:n('RUNNER_RADAR_MIN_5M_VOLUME_USD',1000),runnerRadarMaxAgeMinutes:n('RUNNER_RADAR_MAX_AGE_MINUTES',1440),runnerRadarPriorityBoost:n('RUNNER_RADAR_PRIORITY_BOOST',100),runnerEvidenceThreshold:n('RUNNER_EVIDENCE_THRESHOLD',60),runnerStrongEvidenceThreshold:n('RUNNER_STRONG_EVIDENCE_THRESHOLD',75),runnerMinTrades5m:n('RUNNER_MIN_TRADES_5M',20),runnerMinObservationSeconds:n('RUNNER_MIN_OBSERVATION_SECONDS',45),runnerSnapshotRetentionMinutes:n('RUNNER_SNAPSHOT_RETENTION_MINUTES',180),
  mobulaApiKey:s('MOBULA_API_KEY'),mobulaEnabled:b('MOBULA_ENABLED',true),mobulaTrendingEnabled:b('MOBULA_TRENDING_ENABLED',true),mobulaSafetyEnabled:b('MOBULA_SAFETY_ENABLED',true),mobulaSafetyCacheSeconds:n('MOBULA_SAFETY_CACHE_SECONDS',300),mobulaTrendingLimit:n('MOBULA_TRENDING_LIMIT',50),devHoldingsMediumPct:n('DEV_HOLDINGS_MEDIUM_PCT',7),devHoldingsHighPct:n('DEV_HOLDINGS_HIGH_PCT',15),
  deepSafetyMinScore:n('DEEP_SAFETY_MIN_SCORE',68),
  platformTrendPriorityBoost:n('PLATFORM_TREND_PRIORITY_BOOST',2500),
  analyticsEveryScans:n('ANALYTICS_EVERY_SCANS',10),topRejectedKeep:n('TOP_REJECTED_KEEP',20),candidateSeenCooldownSeconds:n('CANDIDATE_SEEN_COOLDOWN_SECONDS',120),watchTokenAddresses:csv('WATCH_TOKEN_ADDRESSES'),
  revisitScoreEnabled:b('REVISIT_SCORE_ENABLED',true),revisitScoreThreshold:n('REVISIT_SCORE_THRESHOLD',68),revisitScoreIntervalSeconds:n('REVISIT_SCORE_INTERVAL_SECONDS',300),revisitScoreMaxMinutes:n('REVISIT_SCORE_MAX_MINUTES',60),revisitScoreMaxTokens:n('REVISIT_SCORE_MAX_TOKENS',50),
  launchTxLimit:n('LAUNCH_TX_LIMIT',100),launchWindowSeconds:n('LAUNCH_WINDOW_SECONDS',180),minLaunchTxForConfidence:n('MIN_LAUNCH_TX_FOR_CONFIDENCE',4),clusterWalletThreshold:n('CLUSTER_WALLET_THRESHOLD',4),clusterRepeatThreshold:n('CLUSTER_REPEAT_THRESHOLD',3),crowdedSlotsHigh:n('CROWDED_SLOTS_HIGH',2),maxFundingWalletChecks:n('MAX_FUNDING_WALLET_CHECKS',8),fundingHistoryLimit:n('FUNDING_HISTORY_LIMIT',30),fundingLookbackSeconds:n('FUNDING_LOOKBACK_SECONDS',86400),sharedFunderHighWallets:n('SHARED_FUNDER_HIGH_WALLETS',4),bundleSupplyMediumPct:n('BUNDLE_SUPPLY_MEDIUM_PCT',5),bundleSupplyHighPct:n('BUNDLE_SUPPLY_HIGH_PCT',13),blockLowBundleConfidence:b('BLOCK_LOW_BUNDLE_CONFIDENCE',true),holderTop1MediumPct:n('HOLDER_TOP1_MEDIUM_PCT',10),holderTop1HighPct:n('HOLDER_TOP1_HIGH_PCT',20),holderTop5MediumPct:n('HOLDER_TOP5_MEDIUM_PCT',25),holderTop5HighPct:n('HOLDER_TOP5_HIGH_PCT',40),holderTop10MediumPct:n('HOLDER_TOP10_MEDIUM_PCT',40),holderTop10HighPct:n('HOLDER_TOP10_HIGH_PCT',60)
};
export function liveConfigStatus(){const missing=[];if(!config.heliusApiKey)missing.push('HELIUS_API_KEY');if(!config.jupiterApiKey)missing.push('JUPITER_API_KEY');if(!config.bs58PrivateKey)missing.push('BS58_PRIVATE_KEY');if(config.liveAck!=='I_UNDERSTAND_REAL_FUNDS_ARE_AT_RISK')missing.push('LIVE_TRADING_ACK');return{ready:missing.length===0,missing};}
