import fs from "node:fs"; import path from "node:path"; import { config } from "./config.mjs";
fs.mkdirSync(config.dataDir,{recursive:true});
const statePath=path.resolve(config.dataDir,"broke-cat-state.json"); const today=()=>new Date().toISOString().slice(0,10);
export function loadState(){if(fs.existsSync(statePath)){const s=JSON.parse(fs.readFileSync(statePath,"utf8"));if(s.day!==today()){s.day=today();s.dailyPnl=0}return s}return{cash:config.bankroll,realizedPnl:0,dailyPnl:0,day:today(),position:null,trades:[]}}
export function saveState(s){fs.writeFileSync(statePath,JSON.stringify(s,null,2))}
export function openPaper(s,c){if(s.position)return"position already open";if(s.dailyPnl<=-config.maxDailyLoss)return"daily loss limit reached";const size=Math.min(config.maxPosition,s.cash);if(size<=0||c.priceUsd<=0)return"no cash/price";s.cash-=size;s.position={pairAddress:c.pairAddress,tokenAddress:c.tokenAddress,symbol:c.symbol,entryPrice:c.priceUsd,sizeUsd:size,openedAt:new Date().toISOString(),highPrice:c.priceUsd};s.trades.push({type:"BUY",symbol:c.symbol,price:c.priceUsd,sizeUsd:size,score:c.score,at:new Date().toISOString()});saveState(s);return`PAPER BUY $${size.toFixed(2)} ${c.symbol} @ $${c.priceUsd}`}
export function updatePaper(s,price){const p=s.position;if(!p||price<=0)return null;p.highPrice=Math.max(p.highPrice,price);p.lastPrice=price;const ret=price/p.entryPrice-1;let reason=null;if(ret<=-.15)reason="STOP -15%";else if(ret>=.50)reason="TAKE PROFIT +50%";else if(p.highPrice/p.entryPrice>=1.25&&price/p.highPrice<=.88)reason="TRAIL after +25%";if(!reason){saveState(s);return null}const value=p.sizeUsd*(price/p.entryPrice),pnl=value-p.sizeUsd;s.cash+=value;s.realizedPnl+=pnl;s.dailyPnl+=pnl;s.trades.push({type:"SELL",symbol:p.symbol,price,valueUsd:value,pnlUsd:pnl,reason,at:new Date().toISOString()});s.position=null;saveState(s);return`PAPER SELL ${p.symbol}: ${reason} | P&L $${pnl.toFixed(2)} | cash $${s.cash.toFixed(2)}`}
export function stateFilePath(){return statePath}

export function equityUsd(s){if(!s.position)return s.cash;const p=s.position;const mark=Number(p.lastPrice)||p.entryPrice;return s.cash+p.sizeUsd*(mark/p.entryPrice)}
export function tradeStats(s){const sells=s.trades.filter(t=>t.type==="SELL");return{totalTrades:sells.length,wins:sells.filter(t=>Number(t.pnlUsd)>0).length,losses:sells.filter(t=>Number(t.pnlUsd)<0).length}}
