import { config } from './config.mjs';
import { enhancedTransactions, getHolderSnapshot, getMintInfo } from './helius.mjs';
import { birdeyeSafety } from './birdeye_intel.mjs';
import { mobulaSafety } from './mobula_intel.mjs';

const pct=(n,d)=>d>0?n/d*100:0;const uniq=xs=>[...new Set(xs.filter(Boolean))];const asWallet=x=>typeof x==='string'&&x.length>=32?x:null;
function txActors(tx){const actors=[];if(asWallet(tx?.feePayer))actors.push(tx.feePayer);for(const a of tx?.accountData||[])if(a?.nativeBalanceChange<0&&asWallet(a.account))actors.push(a.account);for(const t of tx?.tokenTransfers||[]){if(asWallet(t?.fromUserAccount))actors.push(t.fromUserAccount);if(asWallet(t?.toUserAccount))actors.push(t.toUserAccount)}return uniq(actors)}
function detectLaunchClusters(txs,mint,pairCreatedAt){const createdSec=pairCreatedAt?Math.floor(pairCreatedAt/1000):null;const relevant=txs.filter(t=>!createdSec||!t.timestamp||Math.abs(Number(t.timestamp)-createdSec)<=config.launchWindowSeconds);const slots=new Map(),actorCounts=new Map(),tokenBuyers=new Set();for(const tx of relevant){const actors=txActors(tx);for(const w of actors)actorCounts.set(w,(actorCounts.get(w)||0)+1);if(tx?.slot!=null){const arr=slots.get(tx.slot)||[];arr.push(...actors);slots.set(tx.slot,uniq(arr))}for(const tr of tx?.tokenTransfers||[]){if(tr?.mint!==mint)continue;const to=asWallet(tr?.toUserAccount);if(to)tokenBuyers.add(to)}}const crowdedSlots=[...slots.entries()].filter(([,ws])=>ws.length>=config.clusterWalletThreshold).map(([slot,wallets])=>({slot,wallets}));const repeatedActors=[...actorCounts.entries()].filter(([,count])=>count>=config.clusterRepeatThreshold).map(([wallet,count])=>({wallet,count})).sort((a,b)=>b.count-a.count);const clusterWallets=uniq(crowdedSlots.flatMap(x=>x.wallets));return{txCount:relevant.length,crowdedSlots,repeatedActors,clusterWallets,tokenBuyers:[...tokenBuyers]}}
async function sharedFunders(wallets,launchTimeSec){const capped=uniq(wallets).slice(0,config.maxFundingWalletChecks),funderToWallets=new Map();for(const wallet of capped){try{const txs=await enhancedTransactions(wallet,{limit:config.fundingHistoryLimit,sort:'desc',lteTime:launchTimeSec||undefined,gteTime:launchTimeSec?launchTimeSec-config.fundingLookbackSeconds:undefined,tokenAccounts:'none'});const funders=new Set();for(const tx of txs)for(const tr of tx?.nativeTransfers||[])if(tr?.toUserAccount===wallet&&asWallet(tr?.fromUserAccount)&&Number(tr?.amount||0)>0)funders.add(tr.fromUserAccount);for(const f of funders){const arr=funderToWallets.get(f)||[];arr.push(wallet);funderToWallets.set(f,uniq(arr))}}catch{}}return[...funderToWallets.entries()].filter(([,ws])=>ws.length>=2).map(([funder,wallets])=>({funder,wallets})).sort((a,b)=>b.wallets.length-a.wallets.length)}
export function classifyHolderRisk(snapshot){const{totalSupply,holders}=snapshot;const top1=pct(holders[0]?.amount||0,totalSupply),top5=pct(holders.slice(0,5).reduce((s,h)=>s+h.amount,0),totalSupply),top10=pct(holders.slice(0,10).reduce((s,h)=>s+h.amount,0),totalSupply);let holderRisk='low';if(top1>=config.holderTop1HighPct||top5>=config.holderTop5HighPct||top10>=config.holderTop10HighPct)holderRisk='high';else if(top1>=config.holderTop1MediumPct||top5>=config.holderTop5MediumPct||top10>=config.holderTop10MediumPct)holderRisk='medium';return{holderRisk,holderCount:holders.length,top1Pct:top1,top5Pct:top5,top10Pct:top10,topOwners:holders.slice(0,10)}}
const birdeyeHolderRisk=top10=>top10==null?'unknown':top10>=config.holderTop10HighPct?'high':top10>=config.holderTop10MediumPct?'medium':'low';
const worse=(a,b)=>{const rank={unknown:0,low:1,medium:2,high:3};return(rank[b]||0)>(rank[a]||0)?b:a};
export async function analyzeRisk(c,{deepSafety=false}={}){
  const notes=[];let h=null,hError=null;
  if(config.heliusApiKey){try{const[mintInfo,holders,launchTxs]=await Promise.all([getMintInfo(c.tokenAddress),getHolderSnapshot(c.tokenAddress),enhancedTransactions(c.tokenAddress,{limit:config.launchTxLimit,sort:'asc',tokenAccounts:'all'})]);const holder=classifyHolderRisk(holders),cluster=detectLaunchClusters(launchTxs,c.tokenAddress,c.pairCreatedAt),launchTimeSec=c.pairCreatedAt?Math.floor(c.pairCreatedAt/1000):(launchTxs[0]?.timestamp||null),shared=await sharedFunders(cluster.tokenBuyers.length?cluster.tokenBuyers:cluster.clusterWallets,launchTimeSec),linkedWallets=uniq([...cluster.clusterWallets,...shared.flatMap(x=>x.wallets)]),linkedHeld=holders.holders.filter(x=>linkedWallets.includes(x.owner)).reduce((s,x)=>s+x.amount,0),estimatedLinkedSupplyPct=pct(linkedHeld,holders.totalSupply);let bundleRisk='low';if(shared.some(x=>x.wallets.length>=config.sharedFunderHighWallets)||estimatedLinkedSupplyPct>=config.bundleSupplyHighPct||cluster.crowdedSlots.length>=config.crowdedSlotsHigh)bundleRisk='high';else if(shared.length||estimatedLinkedSupplyPct>=config.bundleSupplyMediumPct||cluster.crowdedSlots.length)bundleRisk='medium';let devRisk='low';if(mintInfo.freezeAuthority||mintInfo.mintAuthority)devRisk='high';const enough=launchTxs.length>=config.minLaunchTxForConfidence,confidence=enough?'medium':'low';if(!enough&&config.blockLowBundleConfidence)bundleRisk='unknown';h={bundleRisk,holderRisk:holder.holderRisk,devRisk,confidence,estimatedLinkedSupplyPct,linkedWalletCount:linkedWallets.length,sharedFunderClusters:shared.length,crowdedLaunchSlots:cluster.crowdedSlots.length,holderCount:holder.holderCount,top1Pct:holder.top1Pct,top5Pct:holder.top5Pct,top10Pct:holder.top10Pct,mintAuthority:mintInfo.mintAuthority,freezeAuthority:mintInfo.freezeAuthority};}catch(e){hError=e?.message||String(e)}}else hError='HELIUS_API_KEY missing';
  let b=null;if(deepSafety&&config.birdeyeSafetyEnabled&&config.birdeyeApiKey){try{b=await birdeyeSafety(c.tokenAddress)}catch(e){notes.push(`Birdeye safety failed: ${e?.message||e}`)}}
  let m=null;if(deepSafety&&config.mobulaSafetyEnabled&&config.mobulaApiKey){try{m=await mobulaSafety(c.tokenAddress)}catch(e){notes.push(`Axiom-style/Mobula safety failed: ${e?.message||e}`)}}
  const bs=b?.summary||{},ms=m?.summary||{};let bundleRisk=h?.bundleRisk||'unknown',holderRisk=h?.holderRisk||'unknown',devRisk=h?.devRisk||'unknown';
  if(bs.firstBuyerCount>=10){const bundlers=bs.tagCounts?.bundler||0,insiders=bs.tagCounts?.insider||0;if(bundlers>=3||insiders>=3)bundleRisk=worse(bundleRisk,'high');else if(bundlers>0||insiders>0)bundleRisk=worse(bundleRisk,'medium');else if(bundleRisk==='unknown'&&bs.firstBuyerCount>=20)bundleRisk='low';notes.push(`Birdeye first buyers: ${bs.firstBuyerCount}; bundler ${bundlers}, sniper ${bs.tagCounts?.sniper||0}, insider ${insiders}, dev ${bs.tagCounts?.dev||0}.`)}
  const bhr=birdeyeHolderRisk(bs.top10Pct);if(bhr!=='unknown')holderRisk=holderRisk==='unknown'?bhr:worse(holderRisk,bhr);
  const mhr=birdeyeHolderRisk(ms.top10Pct);if(mhr!=='unknown')holderRisk=holderRisk==='unknown'?mhr:worse(holderRisk,mhr);
  if(ms.bundlersPct!=null){bundleRisk=ms.bundlersPct>=config.bundleSupplyHighPct?'high':ms.bundlersPct>=config.bundleSupplyMediumPct?worse(bundleRisk,'medium'):(bundleRisk==='unknown'?'low':bundleRisk);notes.push(`Axiom-style bundle ${ms.bundlersPct.toFixed(2)}%.`)}
  if(ms.devPct!=null){devRisk=ms.devPct>=config.devHoldingsHighPct?'high':ms.devPct>=config.devHoldingsMediumPct?worse(devRisk,'medium'):(devRisk==='unknown'?'low':devRisk);notes.push(`Axiom-style dev holding ${ms.devPct.toFixed(2)}%.`)}
  if(ms.insidersPct!=null)notes.push(`Axiom-style insiders ${ms.insidersPct.toFixed(2)}%.`);if(ms.snipersPct!=null)notes.push(`Axiom-style snipers ${ms.snipersPct.toFixed(2)}%.`);
  if(bs.freezeable===true)devRisk='high';else if(devRisk==='unknown'&&bs.freezeable===false)devRisk='low';
  if(bs.creatorPct!=null)notes.push(`Birdeye creator holding ${bs.creatorPct.toFixed(2)}%.`);if(bs.top10Pct!=null)notes.push(`Birdeye top-10 holding ${bs.top10Pct.toFixed(2)}%.`);if(bs.creatorAddress)notes.push(`Creator ${bs.creatorAddress}.`);if(hError)notes.push(`Helius risk path: ${hError}.`);if(b?.errors?.length)notes.push(`Birdeye partial: ${b.errors.join('; ')}.`);
  const confidence=(m?.summary&&(h||b?.enabled))?'high':(h?.confidence==='medium'&&b?.enabled)?'high':h?.confidence||(b?.enabled&&bs.firstBuyerCount>=20?'medium':m?.summary?'medium':'low');
  return{bundleRisk,holderRisk,devRisk,confidence,bundlePct:ms.bundlersPct??null,devHoldingsPct:ms.devPct??bs.creatorPct??null,insidersPct:ms.insidersPct??null,snipersPct:ms.snipersPct??null,estimatedLinkedSupplyPct:h?.estimatedLinkedSupplyPct??null,linkedWalletCount:h?.linkedWalletCount??null,sharedFunderClusters:h?.sharedFunderClusters??null,crowdedLaunchSlots:h?.crowdedLaunchSlots??null,holderCount:ms.holdersCount??h?.holderCount??null,top1Pct:h?.top1Pct??null,top5Pct:h?.top5Pct??null,top10Pct:ms.top10Pct??bs.top10Pct??h?.top10Pct??null,mintAuthority:h?.mintAuthority??null,freezeAuthority:h?.freezeAuthority??null,creatorAddress:bs.creatorAddress??ms.deployer??null,creatorPct:bs.creatorPct??ms.devPct??null,birdeyeFirstBuyerCount:bs.firstBuyerCount??0,birdeyeTagCounts:bs.tagCounts??null,safetySources:[m?.summary?'axiom-style':null,h?'helius':null,b?.enabled?'birdeye':null].filter(Boolean),notes};
}
