import {config} from './config.mjs';import {analyzeRisk} from './risk.mjs';import {runnerMetrics} from './dexscreener.mjs';
const clamp=x=>Math.max(0,Math.min(100,Math.round(x)));
export function classifyLane(c){const age=c.pairCreatedAt?(Date.now()-c.pairCreatedAt)/60000:999999;if(age<=config.earlyMaxAgeMinutes&&c.marketCap<=config.earlyMaxMarketCap)return'Early Cat';if(c.marketCap>=config.momentumMinMarketCap&&(c.volume5m>0||c.priceChange5m>0))return'Momentum Cat';return'Big Potential Cat'}
export function quickScore(c){const age=c.pairCreatedAt?(Date.now()-c.pairCreatedAt)/60000:Infinity;const bs=c.sells5m>0?c.buys5m/c.sells5m:c.buys5m>0?10:0;const accel=c.volume1h>0?c.volume5m/(c.volume1h/12):0;const runner=runnerMetrics(c);let q=0;if(age<=30)q+=15;else if(age<=240)q+=8;if(c.marketCap>=3000&&c.marketCap<=150000)q+=15;if(c.liquidityUsd>=config.minLiquidity)q+=15;if(c.volume5m>=config.min5mVolume)q+=15;if(accel>=1.5)q+=15;if(bs>=1.5)q+=15;if(c.priceChange5m>0)q+=10;if(c.priceChange1h>=config.runnerRadarMin1hChange)q+=15;if(runner.isRunner)q+=25;return clamp(q)}
export async function scoreCandidate(c,hype={bonus:0},cross={bonus:0,sources:[]}){let score=0;const reasons=[];const lane=classifyLane(c);const ageMin=c.pairCreatedAt?(Date.now()-c.pairCreatedAt)/60000:Infinity;const buySell=c.sells5m>0?c.buys5m/c.sells5m:c.buys5m>0?99:0;const accel=c.volume1h>0?c.volume5m/(c.volume1h/12):0;
  if(ageMin<=config.maxTokenAgeMinutes){score+=10;reasons.push(`fresh ${ageMin.toFixed(1)}m`)}
  if(lane==='Early Cat'){if(ageMin<=10)score+=8;if(c.marketCap<=50000)score+=8;reasons.push('early-window')}
  if(c.liquidityUsd>=config.minLiquidity){score+=15;reasons.push('liquidity')}if(c.volume5m>=config.min5mVolume){score+=15;reasons.push('5m volume')}if(accel>=1.5){score+=15;reasons.push(`volume ${accel.toFixed(1)}x`)}if(buySell>=1.5){score+=15;reasons.push(`buy/sell ${buySell.toFixed(1)}x`)}if(c.priceChange5m>0&&c.priceChange5m<=35){score+=10;reasons.push('momentum')}if(c.marketCap>=config.minMarketCap&&c.marketCap<=config.maxMarketCap){score+=10;reasons.push('MC range')}if(c.volume5m>0&&c.liquidityUsd>0&&c.volume5m/c.liquidityUsd<=3){score+=10;reasons.push('volume/liquidity')}
  score+=Number(hype?.bonus||0);if(hype?.bonus)reasons.push(`viral +${hype.bonus}`);score+=Number(cross?.bonus||0);if(cross?.bonus)reasons.push(`cross-platform +${cross.bonus} (${(cross.sources||[]).join(', ')})`);
  const runner=c?.runnerRadar||runnerMetrics(c);if(runner.isRunner){score+=Math.min(18,8+Math.round((runner.evidenceScore-60)/5));reasons.push(`runner evidence ${runner.evidenceScore}/100 (${runner.signals.slice(0,4).join(', ')})`)}else if(runner.evidenceScore>=40){score+=4;reasons.push(`runner watch ${runner.evidenceScore}/100`)}
  const risk=await analyzeRisk(c);if(risk.bundleRisk==='low'){score+=10;reasons.push('low launch-cluster risk')}if(Number(risk.holderCount||0)>=100){score+=4;reasons.push(`${risk.holderCount} holders`)}if(risk.bundleRisk==='medium')score-=15;if(risk.bundleRisk==='high')score-=40;if(risk.devRisk==='high')score-=40;if(risk.holderRisk==='medium')score-=10;if(risk.holderRisk==='high')score-=30;
  return{...c,lane,ageMin,score:clamp(score),risk,reasons,hype,crossPlatform:cross,runnerRadar:runner};}
export function entryAllowed(s){if(s.liquidityUsd<config.minLiquidity)return{ok:false,why:'liquidity below floor'};if(s.marketCap<config.minMarketCap||s.marketCap>config.maxMarketCap)return{ok:false,why:'market cap outside bounds'};if(s.risk.bundleRisk==='unknown')return{ok:false,why:'bundle/launch risk unverified'};if(s.risk.bundleRisk==='high')return{ok:false,why:'high bundle/launch risk'};if(s.risk.devRisk==='high')return{ok:false,why:'high dev authority risk'};if(s.risk.holderRisk==='high')return{ok:false,why:'high holder concentration'};if(s.score<config.minScore)return{ok:false,why:`score ${s.score} < ${config.minScore}`};return{ok:true,why:'approved'};}
