import fs from 'node:fs';import path from 'node:path';import {config} from './config.mjs';
import {authorLaunchTerms,detectScripts,launchSignal,multilingualLaunchQueries,tokenSearchQueries,tokenSearchTerms} from './multilingual.mjs';
const intelPath=path.resolve(config.dataDir,'broke-cat-intel.json');fs.mkdirSync(config.dataDir,{recursive:true});
const CA_RE=/\b[1-9A-HJ-NP-Za-km-z]{32,44}\b/g;
const cache=new Map();
function load(){try{return JSON.parse(fs.readFileSync(intelPath,'utf8'))}catch{return{priorityAddresses:[],prelaunch:[],discoveredAuthors:[],lastRadarAt:null}}}
const state=load();const save=()=>fs.writeFileSync(intelPath,JSON.stringify(state,null,2));
const ready=()=>Boolean(config.xIntelEnabled&&config.xBearerToken);
async function xget(pathname,params={}){if(!ready())return null;const u=new URL(`https://api.x.com${pathname}`);for(const[k,v]of Object.entries(params))if(v!=null&&v!=='')u.searchParams.set(k,String(v));const r=await fetch(u,{headers:{authorization:`Bearer ${config.xBearerToken}`}});if(!r.ok)throw new Error(`X intel ${r.status}: ${await r.text()}`);return r.json()}
function metrics(post){const m=post.public_metrics||{};return Number(m.like_count||0)+2*Number(m.retweet_count||0)+Number(m.reply_count||0)+Number(m.quote_count||0)}
function scorePost(post,user){const followers=Number(user?.public_metrics?.followers_count||0);const engagement=metrics(post);let score=0;if(followers>=100000)score+=35;else if(followers>=25000)score+=25;else if(followers>=5000)score+=15;if(engagement>=1000)score+=35;else if(engagement>=250)score+=25;else if(engagement>=50)score+=15;if(user?.verified)score+=10;if(launchSignal(post.text||''))score+=10;return Math.min(100,score)}
export async function scanPrelaunchRadar(){
  if(!ready())return{enabled:false,newAddresses:[]};
  const now=Date.now();if(state.lastRadarAt&&now-new Date(state.lastRadarAt).getTime()<config.xIntelPollSeconds*1000)return{enabled:true,newAddresses:[]};
  const queries=config.xMultilingualIntelEnabled?multilingualLaunchQueries(config.xPrelaunchQuery,Math.max(1,Math.min(4,config.xMultilingualQueryGroups))):[config.xPrelaunchQuery];
  const watchAuthors=[...new Set([...config.xOfficialWatchAccounts,...(state.discoveredAuthors||[])])].slice(0,10);if(watchAuthors.length){const from=watchAuthors.map(x=>`from:${String(x).replace(/^@/,'')}`).join(' OR ');queries.unshift(`(${from}) ${config.xMultilingualIntelEnabled?authorLaunchTerms():'("contract address" OR "CA" OR "live" OR "launch")'}`)}
  const newAddresses=[],newHighHype=[];
  for(const q of queries.slice(0,5)){
    const data=await xget('/2/tweets/search/recent',{query:q,max_results:25,'tweet.fields':'created_at,public_metrics,author_id,lang','expansions':'author_id','user.fields':'username,verified,created_at,public_metrics'}).catch(()=>null);if(!data)continue;
    const users=new Map((data.includes?.users||[]).map(u=>[u.id,u]));
    for(const post of data.data||[]){const user=users.get(post.author_id);const hype=scorePost(post,user);const cas=[...(post.text||'').matchAll(CA_RE)].map(m=>m[0]);const row={id:post.id,at:post.created_at||new Date().toISOString(),author:user?.username||post.author_id,hype,lang:post.lang||null,scripts:detectScripts(post.text||''),text:String(post.text||'').slice(0,240),contractAddresses:cas};state.prelaunch.push(row);if(hype>=75&&row.author){state.discoveredAuthors=state.discoveredAuthors||[];if(!state.discoveredAuthors.includes(row.author))state.discoveredAuthors.unshift(row.author);newHighHype.push(row)}if(hype>=60)for(const ca of cas){if(!state.priorityAddresses.includes(ca)){state.priorityAddresses.unshift(ca);newAddresses.push(ca)}}}
  }
  state.prelaunch=state.prelaunch.slice(-150);state.priorityAddresses=state.priorityAddresses.slice(0,100);state.discoveredAuthors=(state.discoveredAuthors||[]).slice(0,25);state.lastRadarAt=new Date().toISOString();save();return{enabled:true,multilingual:config.xMultilingualIntelEnabled,newAddresses,newHighHype,top:[...state.prelaunch].sort((a,b)=>b.hype-a.hype).slice(0,5)};
}
export function priorityAddresses(){return[...state.priorityAddresses]}
export async function tokenHype(c){
  if(!ready())return{enabled:false,bonus:0,mentions:0,engagement:0,uniqueAuthors:0,multilingual:false};
  const key=c.tokenAddress;const old=cache.get(key);if(old&&Date.now()-old.at<config.xHypeCacheSeconds*1000)return old.value;
  const queries=config.xMultilingualIntelEnabled?tokenSearchQueries(c):[`(${[`"${String(c.name||'').replace(/["\\]/g,' ')}"`,String(c.symbol||'').length>1&&/^[A-Za-z0-9_]+$/.test(String(c.symbol))?`$${c.symbol}`:'',c.tokenAddress].filter(Boolean).join(' OR ')}) -is:retweet`];
  const postsById=new Map();let anySuccess=false;
  for(const q of queries){const data=await xget('/2/tweets/search/recent',{query:q,max_results:25,'tweet.fields':'created_at,public_metrics,author_id,lang'}).catch(()=>null);if(!data)continue;anySuccess=true;for(const p of data.data||[])postsById.set(p.id,p)}
  if(!anySuccess){const v={enabled:true,error:true,bonus:0,mentions:0,engagement:0,uniqueAuthors:0,multilingual:config.xMultilingualIntelEnabled};cache.set(key,{at:Date.now(),value:v});return v}
  const posts=[...postsById.values()];const engagement=posts.reduce((s,p)=>s+metrics(p),0);const uniqueAuthors=new Set(posts.map(p=>p.author_id).filter(Boolean)).size;const languages=[...new Set(posts.map(p=>p.lang).filter(Boolean))];let bonus=0;if(posts.length>=20)bonus+=5;else if(posts.length>=8)bonus+=3;if(uniqueAuthors>=12)bonus+=4;else if(uniqueAuthors>=5)bonus+=2;if(engagement>=500)bonus+=4;else if(engagement>=100)bonus+=2;if(posts.some(p=>(p.text||'').includes(c.tokenAddress)))bonus+=2;bonus=Math.min(config.viralBonusMax,bonus);const v={enabled:true,bonus,mentions:posts.length,engagement,uniqueAuthors,languages,multilingual:config.xMultilingualIntelEnabled,searchTerms:tokenSearchTerms(c).slice(0,10),scripts:[...new Set([...detectScripts(c.name),...detectScripts(c.symbol)])]};cache.set(key,{at:Date.now(),value:v});return v;
}
export function intelStatus(){return{enabled:ready(),multilingual:config.xMultilingualIntelEnabled,prelaunchCount:state.prelaunch.length,priorityAddressCount:state.priorityAddresses.length,discoveredAuthorCount:(state.discoveredAuthors||[]).length,lastRadarAt:state.lastRadarAt}}
let streamRunning=false,streamLastEventAt=null;
async function rulesRequest(method,body){const r=await fetch('https://api.x.com/2/tweets/search/stream/rules',{method,headers:{authorization:`Bearer ${config.xBearerToken}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(`X stream rules ${r.status}: ${await r.text()}`);return r.json()}
async function configureRules(){const existing=await rulesRequest('GET');const ours=(existing.data||[]).filter(x=>String(x.tag||'').startsWith('broke-cat-v9'));if(ours.length)await rulesRequest('POST',{delete:{ids:ours.map(x=>x.id)}});const add=[];if(config.xOfficialWatchAccounts.length){add.push({value:`(${config.xOfficialWatchAccounts.slice(0,10).map(x=>`from:${x.replace(/^@/,'')}`).join(' OR ')}) ${config.xMultilingualIntelEnabled?authorLaunchTerms():'(CA OR contract OR launch OR live)'}`,tag:'broke-cat-v9-official'})}const radarQueries=config.xMultilingualIntelEnabled?multilingualLaunchQueries(config.xPrelaunchQuery,Math.max(1,Math.min(3,config.xMultilingualQueryGroups))):[config.xPrelaunchQuery];radarQueries.forEach((value,i)=>add.push({value,tag:`broke-cat-v9-radar-${i+1}`}));await rulesRequest('POST',{add});}
export async function startXFilteredStream(onAddress=()=>{}){if(streamRunning||!ready()||!config.xStreamEnabled)return false;streamRunning=true;(async()=>{while(streamRunning){try{await configureRules();const u='https://api.x.com/2/tweets/search/stream?tweet.fields=created_at,author_id,public_metrics,lang';const r=await fetch(u,{headers:{authorization:`Bearer ${config.xBearerToken}`}});if(!r.ok)throw new Error(`X stream ${r.status}: ${await r.text()}`);const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(streamRunning){const{done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});let nl;while((nl=buf.indexOf('\n'))>=0){const line=buf.slice(0,nl).trim();buf=buf.slice(nl+1);if(!line)continue;let evt;try{evt=JSON.parse(line)}catch{continue}const post=evt.data;if(!post?.text)continue;streamLastEventAt=new Date().toISOString();const cas=[...post.text.matchAll(CA_RE)].map(m=>m[0]);for(const ca of cas){if(!state.priorityAddresses.includes(ca)){state.priorityAddresses.unshift(ca);state.priorityAddresses=state.priorityAddresses.slice(0,100);save();onAddress(ca,{...post,scripts:detectScripts(post.text)})}}}}}catch(e){console.error('X filtered stream reconnecting:',e.message);await new Promise(r=>setTimeout(r,5000))}}})();return true}
export function streamStatus(){return{enabled:Boolean(config.xStreamEnabled&&ready()),running:streamRunning,lastEventAt:streamLastEventAt}}
